//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсилиусПоПрактосиус2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КнижныйEntities : DbContext
    {
        public КнижныйEntities()
            : base("name=КнижныйEntities")
        {
        }
        private static КнижныйEntities a;
        public static КнижныйEntities GetContext()
        {
            if (a == null)
            {
                a = new КнижныйEntities();
            }
            return a;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Корзина> Корзина { get; set; }
        public virtual DbSet<лого> лого { get; set; }
        public virtual DbSet<Отдел> Отдел { get; set; }
        public virtual DbSet<Покупатель> Покупатель { get; set; }
        public virtual DbSet<Покупка> Покупка { get; set; }
        public virtual DbSet<Продавец> Продавец { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
