//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсилиусПоПрактосиус2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Корзина()
        {
            this.Покупка = new HashSet<Покупка>();
        }
    
        public int Номер_корзины { get; set; }
        public int ID_товара { get; set; }
        public int Количество { get; set; }
        public Nullable<int> Номер_операции { get; set; }
    
        public virtual Товар Товар { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Покупка> Покупка { get; set; }
    }
}
