//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсилиусПоПрактосиус2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупка
    {
        public int ID_операции { get; set; }
        public int ID_статуса { get; set; }
        public int ID_номер { get; set; }
        public int Индивидуальный_номер_заказа { get; set; }
        public int Номер_корзины { get; set; }
        public double Итоговая_стоимость { get; set; }
    
        public virtual Корзина Корзина { get; set; }
        public virtual Покупатель Покупатель { get; set; }
        public virtual Продавец Продавец { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
